import { useEffect, useState } from "react";
import { History, RefreshCw, Search } from "lucide-react";
import { toast } from "react-hot-toast";
import { Button, Card, Input } from "@/components/ui";
import { listAppointments } from "./appointmentsApi";
import { lifecycleStatusClass } from "@/features/lifecycle/confirmation";

export default function LogsPage() {
  const [rows, setRows] = useState([]);
  const [filters, setFilters] = useState({ from: "", to: "", status: "", search: "" });
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const result = await listAppointments({ ...filters, limit: 100 }); setRows(result?.data || []); } catch (error) { toast.error(error.response?.data?.message || "Failed to load appointment logs"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [filters.from, filters.to, filters.status, filters.search]);
  const update = (field, value) => setFilters((current) => ({ ...current, [field]: value }));
  return <div className="space-y-5" data-tour="appointments-logs-page"><Card title="Appointment Logs" actions={<Button variant="outline" size="sm" onClick={load}><RefreshCw className="h-4 w-4" /> Refresh</Button>}><div className="grid gap-3 md:grid-cols-4" data-tour="appointments-log-filters"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted" /><Input value={filters.search} onChange={(event) => update("search", event.target.value)} placeholder="Token, visitor, purpose" className="pl-9" /></div><Input type="date" value={filters.from} onChange={(event) => update("from", event.target.value)} /><Input type="date" value={filters.to} onChange={(event) => update("to", event.target.value)} /><select value={filters.status} onChange={(event) => update("status", event.target.value)} className="rounded-control border border-border-strong px-3 py-2 text-body"><option value="">All statuses</option><option value="Waiting">Waiting</option><option value="InMeeting">InMeeting</option><option value="Done">Done</option></select></div></Card><Card>{loading ? <p className="py-8 text-center text-body text-secondary">Loading logs...</p> : rows.length === 0 ? <div className="py-10 text-center"><History className="mx-auto mb-2 h-9 w-9 text-muted" /><p className="text-body text-secondary">No appointment logs found.</p></div> : <div className="overflow-x-auto" data-tour="appointments-log-results"><table className="w-full text-left text-body"><thead className="border-b border-border text-small text-secondary"><tr><th className="px-3 py-3">Token</th><th className="px-3 py-3">Visitor</th><th className="px-3 py-3">Purpose</th><th className="px-3 py-3">Host</th><th className="px-3 py-3">Check in</th><th className="px-3 py-3">Check out</th><th className="px-3 py-3">Status</th></tr></thead><tbody className="divide-y divide-border">{rows.map((row) => <tr key={row._id}><td className="px-3 py-3 font-semibold text-accent">{row.tokenNumber}</td><td className="px-3 py-3">{row.visitorName}</td><td className="px-3 py-3">{row.purpose}</td><td className="px-3 py-3">{row.hostEmployeeRef?.name || "—"}</td><td className="px-3 py-3">{row.checkInTime ? new Date(row.checkInTime).toLocaleString() : "—"}</td><td className="px-3 py-3">{row.checkOutTime ? new Date(row.checkOutTime).toLocaleString() : "—"}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-small ${lifecycleStatusClass(row.status)}`}>{row.status}</span></td></tr>)}</tbody></table></div>}</Card></div>;
}
